cp2k:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - dbcsr@2.5.0 smm=libxsmm
  - intel-oneapi-mkl +cluster # Cluster support: scalapack, blacs, ... Use amdscalapack instead?
  - libint@2.6.0 +fortran tune=cp2k-lmax-6
  - libxc@6.1.0
  - pexsi@1.2.0 +fortran
  - elpa@2022.11.001 +mpi
  - sirius@7.3.2 +fortran ~apps
  - cosma@2.5.1 +scalapack
  - libvori@210412
  - spglib@2.0.2
  - libxsmm@1.17
  - spla@1.5.4 +fortran
  mpi:
    spec: cray-mpich
    gpu: Null
tools:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cmake@3.25.2
  - pkgconfig
  - python@3.9
  - py-numpy
