name: cp2k-dlaf-cuda
store: /user-environment
system: hohgant
spack:
  repo: https://github.com/spack/spack.git
  commit: 4edd364a8b38ba617d86a821788c4225bc325b5b 
modules: false
mirror:
  enable: true
  key: /tmp/spack-push-key.gpg
