packages:
    gcc-env:
      compiler:
      - toolchain: gcc
        spec: gcc@11
      unify: true
      specs:
      # Main CMake dependencies
      - intel-mkl++ilp64
      - blaspp ^intel-mkl++ilp64
      - lapackpp ^intel-mkl++ilp64
      - mimalloc
      - fmt
      - camp
      - umpire@5.0.1 ~examples
      - pika +mpi
      - pika-algorithms
      # Optional CMake dependencies
      - googletest
      mpi:
        spec: cray-mpich
        gpu: Null
    tools:
      compiler:
      - toolchain: gcc
        spec: gcc@11
      unify: true
      specs:
      - cmake
      - pkgconfig
      - python@3.9
