gcc-env:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - intel-mkl threads=openmp ^cray-mpich
  # CP2K
  - cosma@2.6.6 +scalapack
  - libint@2.6.0 +fortran tune=cp2k-lmax-5
  - libxc@6.1.0
  - spglib@2.0.2
  - libxsmm@1.17
  - dbcsr@2.5.0 smm=libxsmm +openmp
  - fftw@3.3.10 +mpi +openmp
  # DLAF
  - blaspp ^intel-mkl
  - lapackpp ^intel-mkl
  - mimalloc
  - fmt
  - camp
  - umpire@5.0.1 ~examples
  - pika +mpi
  - pika-algorithms
  - googletest
  mpi:
   spec: cray-mpich
   gpu: null
tools:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cmake@3.25.2
  - pkgconfig
  - git
  - python@3.9
  - doxygen
