namd-a100:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cuda@11.8
  - fftw@3.3.9 +openmp
  - charmpp@6.10.2 backend=multicore +tracing
  - namd@2.14 +cuda cuda_arch=80
  views:
    dev:
      exclude: ["namd"]
    namd:
      exclude: [""]
  mpi:
    spec: cray-mpich
    gpu: cuda
tools:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cmake@3.25.2
  - pkgconfig
