cp2k-dlaf-nvgpu:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cray-mpich
  - cuda@11.8
  - intel-mkl threads=openmp
  - libxc ~cuda
  - dbcsr@develop ~cuda +shared +openmp
  - cosma@master +gpu_direct +scalapack +shared
  - pika@0.20.0
  - dla-future@0.3.0 +scalapack
  - cp2k@master +libxc +libint +spglib +cosma ~elpa +dlaf build_system=cmake
  variants:
    - +mpi
    - +cuda
    - cuda_arch=80
    - build_type=Release
  mpi:
    spec: cray-mpich
    gpu: cuda
cp2k-nvgpu-elpa:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cray-mpich
  - cuda@11.8
  - intel-mkl threads=openmp
  - libxc ~cuda
  - dbcsr@develop ~cuda +shared +openmp
  - cosma@master +gpu_direct +scalapack +shared
  - cp2k@master +libxc +libint +spglib +cosma +elpa ~dlaf build_system=cmake
  variants:
    - +mpi
    - +cuda
    - cuda_arch=80
    - build_type=Release
  mpi:
    spec: cray-mpich
    gpu: cuda
