gcc-env:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  # Main CMake dependencies
  - cuda@11.8
  - intel-mkl threads=openmp
  - blaspp ^intel-mkl threads=openmp
  - lapackpp ^intel-mkl threads=openmp
  - mimalloc
  - fmt
  - camp
  - umpire@5.0.1 +cuda ~examples
  - pika +mpi +cuda
  - pika-algorithms
  - whip +cuda
  # Optional CMake dependencies
  - googletest
  mpi:
    spec: cray-mpich
    gpu: cuda
tools:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cmake@3.25
  - pkgconfig
  - python@3.10
  - doxygen
