cp2k-dlaf-amdgpu:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cray-mpich
  - cmake@3.24.4 # ROCm/HIP?
  - hip@5.2.3
  - mesa ~llvm
  - intel-mkl threads=openmp
  - dbcsr@develop +shared +openmp 
  - cosma@master +gpu_direct +scalapack +shared
  - pika@0.20.0
  - dla-future@master +scalapack
  - cp2k@master +libxc +libint +spglib +cosma ~elpa +dlaf build_system=cmake
  variants:
    - +mpi
    - +rocm
    - amdgpu_target=gfx90a
    - build_type=Release
  mpi:
    spec: cray-mpich
    gpu: rocm
cp2k-nvgpu-elpa:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cray-mpich
  - cmake@3.24.4 # ROCm/HIP?
  - hip@5.2.3
  - mesa ~llvm
  - intel-mkl threads=openmp
  - dbcsr@develop +shared +openmp
  - cosma@master +gpu_direct +scalapack +shared
  - cp2k@master +libxc +libint +spglib +cosma +elpa ~dlaf build_system=cmake
  variants:
    - +mpi
    - +rocm
    - amdgpu_target=gfx90a
    - build_type=Release
  mpi:
    spec: cray-mpich
    gpu: rocm
