cp2k-dlaf-amdgpu:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cmake@3.24.4 # ROCm/HIP?
  - hip@5.2.3
  - hipfft
  - mesa ~llvm
  - intel-mkl threads=openmp
  - libxc
  - dbcsr@develop +shared +openmp ^intel-mkl ^cray-mpich
  - cosma@master +gpu_direct +scalapack +shared ^intel-mkl ^cray-mpich
  - dla-future@master +scalapack
  - cp2k@master +libxc +libint +spglib +cosma ~elpa +dlaf build_system=cmake ^intel-mkl ^cray-mpich ^hipfft
  variants:
    - +mpi
    - +rocm
    - amdgpu_target=gfx90a
    - build_type=Release
  mpi:
    spec: cray-mpich
    gpu: rocm
cp2k-nvgpu-elpa:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cmake@3.24.4 # ROCm/HIP?
  - hip@5.2.3
  - hipfft
  - mesa ~llvm
  - intel-mkl threads=openmp
  - libxc
  - dbcsr@develop +shared +openmp ^intel-mkl ^cray-mpich
  - cosma@master +gpu_direct +scalapack +shared ^intel-mkl ^cray-mpich
  - cp2k@master +libxc +libint +spglib +cosma +elpa ~dlaf build_system=cmake ^intel-mkl ^cray-mpich ^hipfft
  variants:
    - +mpi
    - +rocm
    - amdgpu_target=gfx90a
    - build_type=Release
  mpi:
    spec: cray-mpich
    gpu: rocm
tools:
  compiler:
  - toolchain: gcc
    spec: gcc@11
  unify: true
  specs:
  - cmake@3.24.4 # ROCm/HIP?
  - pkgconfig
  - python@3.10
  - py-numpy
