cp2k-nvgpu:
  compiler:
  - toolchain: gcc
    spec: gcc@12.3
  unify: true
  specs:
  - cuda@12.2 # Can't be newer than driver version for DBCSR
    #  - dla-future@0.4.0 +cuda +scalapack ^cray-mpich
    #  - pika@0.24.0 +cuda ^cray-mpich
  - libxc ~cuda
  - dbcsr@2.6.0 +cuda +shared +openmp ^cray-mpich
  - cosma@2.6.6 +scalapack +shared ^cray-mpich # +gpu_direct
  - elpa ^cray-mpich
  - dbcsr@git.tune_gh200=2.6.0 smm=blas ~examples ^cray-mpich
  - cp2k@git.gh200=develop +libxc +libint +spglib +cosma +elpa ~dlaf build_system=cmake ^cray-mpich
  variants:
    - +mpi
    - +cuda
    - cuda_arch=90
    - build_type=Release
  mpi:
    spec: cray-mpich
    gpu: cuda
